# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/task_tracker_db
spring.datasource.username=root
spring.datasource.password=testingLang28!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=your-256-bit-secret-key-here-make-it-long-and-random
app.jwt.expiration-ms=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html